### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by asmsuechan** [aryankanwar/SpaceBot#1]
Hi, @aryankanwar. I got the invitation to this repo just now but I'm not sure why you send me it. Could you explain what you'd expect to? Or did you make a mistake?

**Comment by aryankanwar** [comment]
I am looking for contributors for this repo.

**Comment by asmsuechan** [comment]
Alright, I got it. I've never experienced such an unexpected invitation, so I'm confusing a little. So I'd like to ask you a few more questions:
(1) How did you find me?
(2) How many people did you send invitations?
(3) How many people accept it?

**Comment by aryankanwar** [comment]
1)Through GitHub, I was looking for active contributors in JS and found you.
2)I've sent to few others for contributions
3)You are the first one  👍

**Comment by asmsuechan** [comment]
Thank you for quick answers. I've not accepted your request yet because I'm still confusing. And another question: What do you expect to me?

I'm ok to work with you because it looks interesting/funny.

**Comment by aryankanwar** [comment]
> 
I'm ok to work with you because it looks interesting/funny.
Thanks for considering it. 

> What do you expect to me?
I would need us to work on improving code/new features and suggestions. 

You can feel free to ask if you still find any confusion.

**Comment by asmsuechan** [comment]
Hey, perhaps, did you reset my commits and force push?

**Comment by aryankanwar** [comment]
Hi, Yes I did just to clean the history i squashed the commits,

**Comment by asmsuechan** [comment]
Stupid. That's a rude attitude to contributors... I don't want to work with you anymore. Bye.

**Comment by aryankanwar** [comment]
I didn't know that I am sorry for that, but that doesn't take away your contribution.
